PREFIX brso: <http://purl.jp/bio/10/brso/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX bmpo: <http://purl.bioontology.org/ontology/BMPO/>

SELECT distinct ?id (group_concat(distinct ?phenotype;separator = ", ") AS ?phenotype) (group_concat(distinct ?reference ;separator = ", ") AS ?reference) (group_concat(distinct ?derived_from;separator = ", ") AS ?derived_from)
FROM <http://iruddat2.nig.ac.jp:8120/silkworm>
WHERE {
    {
        ?Resource a brso:BiologicalResource ;
            dct:identifier ?id ;
            dcterms:isReferencedBy ?reference ;
            brso:derived_from ?derived_from ;
            bmpo:stage_egg ?StageResource .
        ?StageResource a brso:BiologicalResourceEgg ;
            sio:SIO_001279 _:b1 .
        _:b1 a sio:SIO_010056 ;
            rdfs:label ?phenotype .
        filter(LANG(?phenotype) = '')
    } UNION {
        ?Resource a brso:BiologicalResource ;
            dct:identifier ?id ;
            dcterms:isReferencedBy ?reference ;
            brso:derived_from ?derived_from ;
            bmpo:stage_larva ?StageResource .
        ?StageResource a brso:BiologicalResourceLarva ;
            sio:SIO_001279 _:b2 .
        _:b2 a sio:SIO_010056 ;
            rdfs:label ?phenotype .
        filter(LANG(?phenotype) = '')
    } UNION {
        ?Resource a brso:BiologicalResource ;
            dct:identifier ?id ;
            dcterms:isReferencedBy ?reference ;
            brso:derived_from ?derived_from ;
            bmpo:stage_larva ?StageResource .
        ?StageResource a brso:BiologicalResourceLarva ;
            sio:SIO_001279 _:b3 .
        _:b3 a sio:SIO_010056 ;
            rdfs:label ?phenotype .
        filter(LANG(?phenotype) = '{{language}}')
    } UNION {
        ?Resource a brso:BiologicalResource ;
            dct:identifier ?id ;
            dcterms:isReferencedBy ?reference ;
            brso:derived_from ?derived_from ;
            bmpo:stage_pupa ?StageResource .
        ?StageResource a brso:BiologicalResourcePupa ;
            sio:SIO_001279 _:b4 .
        _:b4 a sio:SIO_010056 ;
            rdfs:label ?phenotype .
        filter(LANG(?phenotype) = '')
    } UNION {
        ?Resource a brso:BiologicalResource ;
            dct:identifier ?id ;
            dcterms:isReferencedBy ?reference ;
            brso:derived_from ?derived_from ;
            bmpo:stage_adult ?StageResource .
        ?StageResource a brso:BiologicalResourceAdult ;
            sio:SIO_001279 _:b5 .
        _:b5 a sio:SIO_010056 ;
            rdfs:label ?phenotype .
        filter(LANG(?phenotype) = '')
    }
    {
        SELECT distinct ?id
        WHERE {
            {
                ?Resource a brso:BiologicalResource ;
                    dct:identifier ?id ;
                    dcterms:isReferencedBy ?reference ;
                    brso:derived_from ?derived_from ;
                    bmpo:stage_egg ?StageResource .
                ?StageResource a brso:BiologicalResourceEgg ;
                    sio:SIO_001279 _:b6 .
                _:b6 a sio:SIO_010056 ;
                    sio:SIO_000255 ?class .
                filter regex(?class, "{{uri}}", "i")
            } UNION {
                ?Resource a brso:BiologicalResource ;
                    dct:identifier ?id ;
                    dcterms:isReferencedBy ?reference ;
                    brso:derived_from ?derived_from ;
                    bmpo:stage_egg ?StageResource .
                ?StageResource a brso:BiologicalResourceEgg ;
                    sio:SIO_001279 _:b7 .
                _:b7 a sio:SIO_010056 ;
                    rdfs:seeAlso ?class .
                filter regex(?class, "{{uri}}", "i")
            } UNION {
                ?Resource a brso:BiologicalResource ;
                    dct:identifier ?id ;
                    dcterms:isReferencedBy ?reference ;
                    brso:derived_from ?derived_from ;
                    bmpo:stage_larva ?StageResource .
                ?StageResource a brso:BiologicalResourceLarva ;
                    sio:SIO_001279 _:b8 .
                _:b8 a sio:SIO_010056 ;
                    sio:SIO_000255 ?class .
                filter regex(?class, "{{uri}}", "i")
            } UNION {
                ?Resource a brso:BiologicalResource ;
                    dct:identifier ?id ;
                    dcterms:isReferencedBy ?reference ;
                    brso:derived_from ?derived_from ;
                    bmpo:stage_larva ?StageResource .
                ?StageResource a brso:BiologicalResourceLarva ;
                    sio:SIO_001279 _:b9 .
                _:b9 a sio:SIO_010056 ;
                    rdfs:seeAlso ?class .
                filter regex(?class, "{{uri}}", "i")
            } UNION {
                ?Resource a brso:BiologicalResource ;
                    dct:identifier ?id ;
                    dcterms:isReferencedBy ?reference ;
                    brso:derived_from ?derived_from ;
                    bmpo:stage_pupa ?StageResource .
                ?StageResource a brso:BiologicalResourcePupa ;
                    sio:SIO_001279 _:b10 .
                _:b10 a sio:SIO_010056 ;
                    sio:SIO_000255 ?class .
                filter regex(?class, "{{uri}}", "i")
            } UNION {
                ?Resource a brso:BiologicalResource ;
                    dct:identifier ?id ;
                    dcterms:isReferencedBy ?reference ;
                    brso:derived_from ?derived_from ;
                    bmpo:stage_pupa ?StageResource .
                ?StageResource a brso:BiologicalResourcePupa ;
                    sio:SIO_001279 _:b11 .
                _:b11 a sio:SIO_010056 ;
                    rdfs:seeAlso ?class .
                filter regex(?class, "{{uri}}", "i")
            } UNION {
                ?Resource a brso:BiologicalResource ;
                    dct:identifier ?id ;
                    dcterms:isReferencedBy ?reference ;
                    brso:derived_from ?derived_from ;
                    bmpo:stage_adult ?StageResource .
                ?StageResource a brso:BiologicalResourceAdult ;
                    sio:SIO_001279 _:b12 .
                _:b12 a sio:SIO_010056 ;
                    sio:SIO_000255 ?class .
                filter regex(?class, "{{uri}}", "i")
            } UNION {
                ?Resource a brso:BiologicalResource ;
                    dct:identifier ?id ;
                    dcterms:isReferencedBy ?reference ;
                    brso:derived_from ?derived_from ;
                    bmpo:stage_adult ?StageResource .
                ?StageResource a brso:BiologicalResourceAdult ;
                    sio:SIO_001279 _:b13 .
                _:b13 a sio:SIO_010056 ;
                    rdfs:seeAlso ?class .
                filter regex(?class, "{{uri}}", "i")
            }
        }
    }
}
ORDER BY ?id
